### ISSUE TITLE
Enhance Deployment via Declarative IAC 

### ISSUE THREAD

**Issue by jrampono** [microsoft/azure-data-services-go-fast-codebase#103]
Enhance the deployment process using declarative infrastructure as code. Core objectives:

- [x] Simplify Deployment
- [x] Decrease deployment time
- [x] Improve Incremental Deployment Ability
- [x] Reduce Powershell codebase

**Comment by LeighS** [comment]
Implemented in #116

**Comment by LeighS** [comment]
Codebase has been updated to include new terraform modules for deploying platfrom infrastructure. #116
