### ISSUE TITLE
Addition of SIF aligned 3NF base tables

### ISSUE THREAD

**Issue by jrampono** [microsoft/azure-data-services-go-fast-codebase#107]
- [ ] Decide which technology to use for these entities (Data Lake, SQL etc)
- [ ] Decide which technology to host transformations
- [ ] Build IAC scripts
- [ ] Build seed data for functional tests and samples.

**Comment by leonbravo** [comment]
The focus will be on a subset of SIF use cases that forms the core of the data that BCE (and others) will require for the core entity model. These are:
•	Enrollment (Student Data)
•	Attendance
•	Time Table (Classes, Subject) 
•	Assessment

**Comment by leonbravo** [comment]
> * [ ]  Decide which technology to use for these entities (Data Lake, SQL etc)
> 
>     * [ ]  Decide which technology to host transformations
> 
>     * [ ]  Build IAC scripts
> 
>     * [ ]  Build seed data for functional tests and samples.

1. Data Lake
2. Databricks notebooks 
3. @jrampono  we have done the first deployment and would add IAC as required.
4. Sample data created as  json files
