### ISSUE TITLE
Completion of "FileSystem to Azure Storage" Task Type (currently WIP) including functional tests

### ISSUE THREAD

**Issue by jrampono** [microsoft/azure-data-services-go-fast-codebase#190]
- [x] #196
- [x] #197

**Comment by cyrilgagnaire** [comment]
- [ ] Register Self-Hosted Integration Runtime
- [ ] Functional Test - File Server to Azure Blob
- [ ] Functional Test - File Server to SQL Database
- [ ] Functional Test - File Server to File Server

**Comment by cyrilgagnaire** [comment]
@jrampono @andorvarga happy with those subtasks above? If so, I'll convert them into issues. I will do combination of format type under each Functional Tests (Binary, csv, json, parquet, etc...)

**Comment by jrampono** [comment]
> @jrampono @andorvarga happy with those subtasks above? If so, I'll convert them into issues. I will do combination of format type under each Functional Tests (Binary, csv, json, parquet, etc...)

Yup all good. I have removed the second one though as its not needed.
