### ISSUE TITLE
Option to specify delimiter for delimited text

### ISSUE THREAD

**Issue by daviewales** [microsoft/azure-data-services-go-fast-codebase#271]
**Is your feature request related to a problem? Please describe.**
Azure Data Factory has an option to specify the delimiter type when transforming delimited text.
However, I can't see an option in the ADS Go Fast frontend to configure a Task Master to use a delimiter other than 'comma'.

**Describe the solution you'd like**
An option to specify the delimiter type for a Task Master in the frontend.

**Describe alternatives you've considered**
Just using Azure Data Factory directly.

**Comment by jrampono** [comment]
Thanks David, have added this to the enhancement requests backlog

**Comment by jrampono** [comment]
Adding feature to v2.0.2

**Comment by daviewales** [comment]
Thank you!
