### ISSUE TITLE
Cannot execute Spark Notebook and failed to display Task Instance result.

### ISSUE THREAD

**Issue by seanyanglab3** [microsoft/azure-data-services-go-fast-codebase#275]
**Describe the bug**
Bug 1: SparkNote book cannot executed. Azure Function AdfRunFrameworkTasksHttpTrigger log shows: cannot find Synapse GPL_SparkNotebookExecution_Azure pipeline.

Temporary fix: clone or rename pipeline GPL_SparkNotebookExecution_NotebookActivity_Azure to GPL_SparkNotebookExecution_Azure

Bug 2: After Spark notebook execution, web page cannot display Task Instance list. Due to the status 'Succeeded' is not on the icon list.

Fix suggestion: 

Update IndexDataTable.cshtml of TaskInstance. and any view pages which need to display pipeline status.

from line 62 add:
                {
                    extend: 'selected',
                    className: 'btn-success ads-btn-action',
                    text: '<i data-toggle="tooltip" title="Mark as Complete" class="fas fa-flag-checkered" style="width:16px"></i>',
                    action: function (e, dt, node, config) {
                        UpdateTaskInstanceStatus(dt, "Succeeded");
                    }
                },

**Comment by seanyanglab3** [comment]
screenshots of the issues and workaround fix.

![image](https://user-images.githubusercontent.com/85604252/202048408-2c575509-3d43-4e57-a576-f092d6ee1bc2.png)

![image](https://user-images.githubusercontent.com/85604252/202048370-6c9f8567-2961-47af-8b6a-5135d06dc643.png)

![image](https://user-images.githubusercontent.com/85604252/202048320-a53a38b6-ea6d-4b68-93bc-cd45571d6b9c.png)

**Comment by jrampono** [comment]
This is an issue with the deployment environment. Not all of the required Synapse pipelines have been published.
