### ISSUE TITLE
Reported Hubspot Token Exposure

### ISSUE THREAD

**Issue by jrampono** [microsoft/azure-data-services-go-fast-codebase#290]
**Problem:** Reporting token exposure in notebook code:
[solution/Synapse/Patterns/notebook/RestAPINotebook.ipynb](solution/Synapse/Patterns/notebook/RestAPINotebook.ipynb)

**Comment by hugosharpe-insight** [comment]
Token was located in the RestAPINotebook.ipynb. Token has been removed in feature 2.0.3

Notes:
- Token was dead at initial upload.
- Token was a development only token used in the purpose of an example in the notebook.

https://github.com/microsoft/azure-data-services-go-fast-codebase/blob/feature-2.0.3/solution/Synapse/Patterns/notebook/RestAPINotebook.ipynb
Above is the location of the notebook, with the reported dummy token now replaced with 'xxxxxxxxxxxxx'

**Comment by jrampono** [comment]
Merged into main https://github.com/microsoft/azure-data-services-go-fast-codebase/pull/291

**Comment by jrampono** [comment]
https://github.com/microsoft/azure-data-services-go-fast-codebase/pull/291
