### ISSUE TITLE
Making number of IRs  configurable

### ISSUE THREAD

**Issue by jrampono** [microsoft/azure-data-services-go-fast-codebase#32]

**Comment by LeighS** [comment]
Integration Runtimes are now configurable within the Terraform module.   
[https://github.com/microsoft/azure-data-services-go-fast-codebase/blob/main/solution/DeploymentV2/terraform/locals.tf](https://github.com/microsoft/azure-data-services-go-fast-codebase/blob/main/solution/DeploymentV2/terraform/locals.tf)

The DbUp component has also been updated to support parameterising scripts to use appropriate IR details.

**Comment by LeighS** [comment]
Integration Runtimes are now configurable within the Terraform module.  [#116](https://github.com/microsoft/azure-data-services-go-fast-codebase/pull/116)  
[https://github.com/microsoft/azure-data-services-go-fast-codebase/blob/main/solution/DeploymentV2/terraform/locals.tf](https://github.com/microsoft/azure-data-services-go-fast-codebase/blob/main/solution/DeploymentV2/terraform/locals.tf)

The DbUp component has also been updated to support parameterising scripts to use appropriate IR details.
