### ISSUE TITLE
Synapse as Data-sink

### ISSUE THREAD

**Issue by jrampono** [microsoft/azure-data-services-go-fast-codebase#33]
- [x] Addition of Synapse Workspace as part of CICD
- [x] Adding ADF Pipeline Templates to load data into synapse

**Comment by LeighS** [comment]
Added Azure Synapse support #140 

*   Implemented using Terraform
*   Uses azure data lake storage account
*   Added private DNS zones to support private / restricted vnet mode
*   Added Synapse Workspave
*   Added Configurable Synapse SQL Dedicated Pool
*   Added Configurable Synapse Spark Pool
*   Supports custom names
*   Supports feature toggleable components

Synapse Sink Support #176, #177 

Note on Synapse Sink --> Synapse Sink PR for reference available here:

*   [Feature/synapse sink](https://github.com/microsoft/azure-data-services-go-fast-codebase/pull/177) 

John is integrating into his existing in-progress work on Synapse.
