### ISSUE TITLE
Add TaskMaster JSON Schemas to deployment scripts

### ISSUE THREAD

**Issue by jrampono** [microsoft/azure-data-services-go-fast-codebase#40]

**Comment by LeighS** [comment]
@jrampono has introduced jsonnet (https://jsonnet.org/) to generate all pipelines, tests and schemas for the solution. The code for this is under (DataFactory\\Patterns\\Jsonnet\_GenerateADFArtefacts.ps1).

Additionally, the DbUp tool has been updated to insert the schema data.
