### ISSUE TITLE
General UI Testing and Enhancements

### ISSUE THREAD

**Issue by jrampono** [microsoft/azure-data-services-go-fast-codebase#51]
Tasks / General Enhancements / Bugfixes completed by Arkahna as a part of Lockbox V2.0 phase

*   [x] #91 
*   [x] #92 
*   [x] #95 
*   [x] #96 
*   [x] #101 
*   [x] #102 
*   [x] #126 
*   [x] #128 
*   [x] #129 
*   [x] #130 
*   [x] #131 
*   [x] #135 
*   [x] #136 
*   [x] #137 
*   [x] #138 
*   [x] #139 
*   [x] #141 
*   [x] #144 
*   [x] #145 
*   [x] #147 
*   [x] #148 
*   [x] #149 
*   [x] #159 
*   [x] #162

**Comment by LeighS** [comment]
Completed as per associated PRs.
