### ISSUE TITLE
Deploy and Configure Synapse Workspace (ARM, Powershell)

### ISSUE THREAD

**Issue by MaheshSQL** [microsoft/azure-data-services-go-fast-codebase#63]
Provide ability to deploy Synapse Workspace, default storage account, Spark Pool, Dedicated SQL Pool.
All configurations should be customizable via environment.json config and could be partly enabled/disabled.

This will allow for development of Synapse Data Sink pipeline within the ADS GF ADF Pipelines.

**Comment by LeighS** [comment]
Hey Mahesh, I have a few questions about this issue.

*   Is this a platform level Synapse workspace to replace ADF or is this a user provided workspace? 
*   If it is a user provided workspace, what features are you going to deploy and configure?

I am going to be working on a related issue (#33) but I'm keen to understand more about what you are working on here first.

**Comment by MaheshSQL** [comment]
Hi Leigh.

1. We could replace ADF, but intent of this issue is to provision a fresh workspace along with ADS GF suite of services.
2. By default, with Synapse workspace deployment (if enabled), it provisions a Spark Pool, 3 nodes, 15 min auto pause. SQL Dedicated Pool can be provisioned as well (Disabled by default). And the required ADLS Gen2 storage account for the the workspace.

Coincidently, I have just submitted PR (below) of the above into development/0.1 which you can review for details.
https://github.com/microsoft/azure-data-services-go-fast-codebase/pull/90

**Comment by MaheshSQL** [comment]
Closed by #90
