### ISSUE TITLE
Enhance web app source/target system pages with dropdowns for enums

### ISSUE THREAD

**Issue by eseefeld** [microsoft/azure-data-services-go-fast-codebase#97]
When adding or editing source/target systems, some of the inputs are currently text boxes where pre-defined values are expected, for example "System Auth Type". Pease could these be converted to dropdown lists limited to the expected values.

**Comment by LeighS** [comment]
Converted Input SystemAuthType to Select SystemAuthType to allow easier selection.  
Created a function to generate the list for the dropdown
